// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usergrpc.proto

package usergrpcpb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	JobTitle             string   `protobuf:"bytes,6,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Privilege            string   `protobuf:"bytes,7,opt,name=privilege,proto3" json:"privilege,omitempty"`
	Dob                  string   `protobuf:"bytes,8,opt,name=dob,proto3" json:"dob,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,9,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	DataCreated          string   `protobuf:"bytes,10,opt,name=data_created,json=dataCreated,proto3" json:"data_created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *User) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *User) GetPrivilege() string {
	if m != nil {
		return m.Privilege
	}
	return ""
}

func (m *User) GetDob() string {
	if m != nil {
		return m.Dob
	}
	return ""
}

func (m *User) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func (m *User) GetDataCreated() string {
	if m != nil {
		return m.DataCreated
	}
	return ""
}

type UserSave struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	JobTitle             string   `protobuf:"bytes,5,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Privilege            string   `protobuf:"bytes,6,opt,name=privilege,proto3" json:"privilege,omitempty"`
	Dob                  string   `protobuf:"bytes,7,opt,name=dob,proto3" json:"dob,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,8,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	Password             string   `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSave) Reset()         { *m = UserSave{} }
func (m *UserSave) String() string { return proto.CompactTextString(m) }
func (*UserSave) ProtoMessage()    {}
func (*UserSave) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{1}
}

func (m *UserSave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSave.Unmarshal(m, b)
}
func (m *UserSave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSave.Marshal(b, m, deterministic)
}
func (m *UserSave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSave.Merge(m, src)
}
func (m *UserSave) XXX_Size() int {
	return xxx_messageInfo_UserSave.Size(m)
}
func (m *UserSave) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSave.DiscardUnknown(m)
}

var xxx_messageInfo_UserSave proto.InternalMessageInfo

func (m *UserSave) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserSave) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserSave) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserSave) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UserSave) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *UserSave) GetPrivilege() string {
	if m != nil {
		return m.Privilege
	}
	return ""
}

func (m *UserSave) GetDob() string {
	if m != nil {
		return m.Dob
	}
	return ""
}

func (m *UserSave) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func (m *UserSave) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{2}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{3}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SaveUserRequest struct {
	UserSave             *UserSave `protobuf:"bytes,1,opt,name=userSave,proto3" json:"userSave,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SaveUserRequest) Reset()         { *m = SaveUserRequest{} }
func (m *SaveUserRequest) String() string { return proto.CompactTextString(m) }
func (*SaveUserRequest) ProtoMessage()    {}
func (*SaveUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{4}
}

func (m *SaveUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveUserRequest.Unmarshal(m, b)
}
func (m *SaveUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveUserRequest.Marshal(b, m, deterministic)
}
func (m *SaveUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveUserRequest.Merge(m, src)
}
func (m *SaveUserRequest) XXX_Size() int {
	return xxx_messageInfo_SaveUserRequest.Size(m)
}
func (m *SaveUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveUserRequest proto.InternalMessageInfo

func (m *SaveUserRequest) GetUserSave() *UserSave {
	if m != nil {
		return m.UserSave
	}
	return nil
}

type SaveUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveUserResponse) Reset()         { *m = SaveUserResponse{} }
func (m *SaveUserResponse) String() string { return proto.CompactTextString(m) }
func (*SaveUserResponse) ProtoMessage()    {}
func (*SaveUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{5}
}

func (m *SaveUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveUserResponse.Unmarshal(m, b)
}
func (m *SaveUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveUserResponse.Marshal(b, m, deterministic)
}
func (m *SaveUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveUserResponse.Merge(m, src)
}
func (m *SaveUserResponse) XXX_Size() int {
	return xxx_messageInfo_SaveUserResponse.Size(m)
}
func (m *SaveUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveUserResponse proto.InternalMessageInfo

func (m *SaveUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type FindByEmailAndPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByEmailAndPasswordRequest) Reset()         { *m = FindByEmailAndPasswordRequest{} }
func (m *FindByEmailAndPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*FindByEmailAndPasswordRequest) ProtoMessage()    {}
func (*FindByEmailAndPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{6}
}

func (m *FindByEmailAndPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByEmailAndPasswordRequest.Unmarshal(m, b)
}
func (m *FindByEmailAndPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByEmailAndPasswordRequest.Marshal(b, m, deterministic)
}
func (m *FindByEmailAndPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByEmailAndPasswordRequest.Merge(m, src)
}
func (m *FindByEmailAndPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_FindByEmailAndPasswordRequest.Size(m)
}
func (m *FindByEmailAndPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByEmailAndPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByEmailAndPasswordRequest proto.InternalMessageInfo

func (m *FindByEmailAndPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *FindByEmailAndPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type FindByEmailAndPasswordResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByEmailAndPasswordResponse) Reset()         { *m = FindByEmailAndPasswordResponse{} }
func (m *FindByEmailAndPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*FindByEmailAndPasswordResponse) ProtoMessage()    {}
func (*FindByEmailAndPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{7}
}

func (m *FindByEmailAndPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByEmailAndPasswordResponse.Unmarshal(m, b)
}
func (m *FindByEmailAndPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByEmailAndPasswordResponse.Marshal(b, m, deterministic)
}
func (m *FindByEmailAndPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByEmailAndPasswordResponse.Merge(m, src)
}
func (m *FindByEmailAndPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_FindByEmailAndPasswordResponse.Size(m)
}
func (m *FindByEmailAndPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByEmailAndPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindByEmailAndPasswordResponse proto.InternalMessageInfo

func (m *FindByEmailAndPasswordResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{8}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type DeleteUserResponse struct {
	ConfirmDelete        bool     `protobuf:"varint,1,opt,name=confirmDelete,proto3" json:"confirmDelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{9}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetConfirmDelete() bool {
	if m != nil {
		return m.ConfirmDelete
	}
	return false
}

type UpdateUserRequest struct {
	UserSave             *UserSave `protobuf:"bytes,1,opt,name=userSave,proto3" json:"userSave,omitempty"`
	Email                string    `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{10}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUserSave() *UserSave {
	if m != nil {
		return m.UserSave
	}
	return nil
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b2fcb8862490326, []int{11}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "usergrpc.User")
	proto.RegisterType((*UserSave)(nil), "usergrpc.UserSave")
	proto.RegisterType((*GetUserRequest)(nil), "usergrpc.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "usergrpc.GetUserResponse")
	proto.RegisterType((*SaveUserRequest)(nil), "usergrpc.SaveUserRequest")
	proto.RegisterType((*SaveUserResponse)(nil), "usergrpc.SaveUserResponse")
	proto.RegisterType((*FindByEmailAndPasswordRequest)(nil), "usergrpc.FindByEmailAndPasswordRequest")
	proto.RegisterType((*FindByEmailAndPasswordResponse)(nil), "usergrpc.FindByEmailAndPasswordResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "usergrpc.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "usergrpc.DeleteUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "usergrpc.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "usergrpc.UpdateUserResponse")
}

func init() { proto.RegisterFile("usergrpc.proto", fileDescriptor_9b2fcb8862490326) }

var fileDescriptor_9b2fcb8862490326 = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x55, 0x9c, 0x2f, 0x67, 0xda, 0xa6, 0xed, 0x0a, 0x55, 0x8b, 0xdb, 0xa2, 0x62, 0x21, 0x08,
	0x97, 0x1c, 0x8a, 0x40, 0x88, 0x03, 0x52, 0x4a, 0xa1, 0xe2, 0x82, 0x20, 0x90, 0x03, 0x5c, 0xa2,
	0x75, 0x3c, 0x29, 0x2e, 0x8e, 0xd7, 0xec, 0x6e, 0x8a, 0xf8, 0x11, 0x1c, 0xf8, 0xbb, 0x9c, 0xd0,
	0xae, 0x1d, 0xdb, 0x49, 0xec, 0x94, 0x8a, 0x5b, 0xe6, 0xbd, 0x99, 0xb7, 0x99, 0x37, 0x4f, 0x09,
	0x74, 0xe7, 0x12, 0xc5, 0xa5, 0x88, 0x27, 0xfd, 0x58, 0x70, 0xc5, 0x89, 0xbd, 0xa8, 0xdd, 0x5f,
	0x16, 0x34, 0x46, 0x12, 0x05, 0xe9, 0x82, 0x15, 0xf8, 0xb4, 0x76, 0x52, 0xeb, 0xd5, 0x87, 0x56,
	0xe0, 0x93, 0x3b, 0xd0, 0xc4, 0x19, 0x0b, 0x42, 0x6a, 0x9d, 0xd4, 0x7a, 0x9d, 0x61, 0x52, 0x90,
	0x43, 0xe8, 0x84, 0x4c, 0xaa, 0x71, 0xc4, 0x66, 0x48, 0xeb, 0x86, 0xb1, 0x35, 0xf0, 0x8e, 0xcd,
	0x90, 0x1c, 0x03, 0x4c, 0x03, 0xb1, 0x60, 0x1b, 0x86, 0xed, 0x18, 0xc4, 0xd0, 0x07, 0xd0, 0x92,
	0x8a, 0xa9, 0xb9, 0xa4, 0x4d, 0x43, 0xa5, 0x95, 0xd6, 0xbc, 0xe2, 0xde, 0x58, 0x05, 0x2a, 0x44,
	0xda, 0x4a, 0x34, 0xaf, 0xb8, 0xf7, 0x49, 0xd7, 0xe4, 0x08, 0x3a, 0xb1, 0x08, 0xae, 0x83, 0x10,
	0x2f, 0x91, 0xb6, 0x13, 0xc9, 0x0c, 0x20, 0x7b, 0x50, 0xf7, 0xb9, 0x47, 0x6d, 0x83, 0xeb, 0x8f,
	0x5a, 0x2c, 0xfe, 0xca, 0x15, 0x1f, 0xcf, 0x45, 0x48, 0x3b, 0x89, 0x98, 0x01, 0x46, 0x22, 0x24,
	0xf7, 0x61, 0xdb, 0x67, 0x8a, 0x8d, 0x27, 0x02, 0x99, 0x42, 0x9f, 0x82, 0xe1, 0xb7, 0x34, 0xf6,
	0x2a, 0x81, 0xdc, 0x3f, 0x35, 0xb0, 0xb5, 0x1f, 0x1f, 0xd9, 0x35, 0xe6, 0x1e, 0xd4, 0x2a, 0x3d,
	0xb0, 0x36, 0x7a, 0x50, 0xaf, 0xf6, 0xa0, 0x51, 0xed, 0x41, 0x73, 0x93, 0x07, 0xad, 0x0a, 0x0f,
	0xda, 0x15, 0x1e, 0xd8, 0x2b, 0x1e, 0x38, 0x60, 0xc7, 0x4c, 0xca, 0x1f, 0x5c, 0xf8, 0x99, 0x3f,
	0x69, 0xed, 0x3e, 0x84, 0xee, 0x05, 0x2a, 0xbd, 0xfe, 0x10, 0xbf, 0xcf, 0x51, 0xaa, 0x72, 0x07,
	0xdc, 0xa7, 0xb0, 0x9b, 0xf5, 0xc9, 0x98, 0x47, 0x12, 0x89, 0x0b, 0x0d, 0x9d, 0x29, 0xd3, 0xb7,
	0x75, 0xda, 0xed, 0x67, 0x81, 0x33, 0x5d, 0x86, 0x73, 0x07, 0xb0, 0xab, 0x6d, 0x2d, 0xea, 0xf7,
	0xc1, 0x44, 0x51, 0xc3, 0xe9, 0x28, 0x59, 0x1e, 0xd5, 0xcc, 0x30, 0xeb, 0x71, 0x9f, 0xc1, 0x5e,
	0x2e, 0x71, 0x8b, 0xa7, 0x3f, 0xc0, 0xf1, 0x9b, 0x20, 0xf2, 0xcf, 0x7e, 0xbe, 0xd6, 0x0b, 0x0c,
	0x22, 0xff, 0x7d, 0xba, 0xf3, 0xc6, 0x45, 0x97, 0xcc, 0xb2, 0x56, 0xcc, 0x3a, 0x87, 0x7b, 0x55,
	0x92, 0xb7, 0xf8, 0x62, 0x8f, 0x61, 0xff, 0x1c, 0x43, 0x54, 0x78, 0xb3, 0xeb, 0x2f, 0x80, 0x14,
	0x5b, 0xd3, 0x47, 0x1e, 0xc0, 0xce, 0x84, 0x47, 0xd3, 0x40, 0xcc, 0x12, 0xd2, 0xcc, 0xd8, 0xc3,
	0x65, 0xd0, 0xfd, 0x0c, 0xfb, 0xa3, 0xd8, 0x67, 0xea, 0x7f, 0xcc, 0x2f, 0xff, 0x49, 0x70, 0x9f,
	0x03, 0x29, 0x4a, 0xff, 0xfb, 0xee, 0xa7, 0xbf, 0xeb, 0xb0, 0xa3, 0xcb, 0xb7, 0x91, 0x42, 0x31,
	0x65, 0x13, 0x24, 0x2f, 0xa1, 0x9d, 0x06, 0x8b, 0xd0, 0x7c, 0x64, 0x39, 0x93, 0xce, 0xdd, 0x12,
	0x26, 0x7d, 0x75, 0x00, 0xf6, 0x22, 0x1e, 0xa4, 0xd0, 0xb6, 0x92, 0x3a, 0xc7, 0x29, 0xa3, 0x52,
	0x89, 0x6f, 0x70, 0x50, 0x7e, 0x56, 0xf2, 0x28, 0x9f, 0xda, 0x98, 0x25, 0xa7, 0x77, 0x73, 0x63,
	0xfa, 0xd8, 0x05, 0x40, 0x7e, 0x52, 0x72, 0x98, 0xcf, 0xad, 0x65, 0xc2, 0x39, 0x2a, 0x27, 0x73,
	0xa1, 0xfc, 0x08, 0x45, 0xa1, 0xb5, 0xab, 0x17, 0x85, 0xd6, 0xef, 0x76, 0xb6, 0xfd, 0x05, 0x16,
	0x74, 0xec, 0x79, 0x2d, 0xf3, 0x77, 0xf1, 0xe4, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x16, 0x44,
	0x14, 0x9b, 0x40, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserInterfaceClient is the client API for UserInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserInterfaceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	SaveUser(ctx context.Context, in *SaveUserRequest, opts ...grpc.CallOption) (*SaveUserResponse, error)
	FindByEmailAndPassword(ctx context.Context, in *FindByEmailAndPasswordRequest, opts ...grpc.CallOption) (*FindByEmailAndPasswordResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
}

type userInterfaceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserInterfaceClient(cc grpc.ClientConnInterface) UserInterfaceClient {
	return &userInterfaceClient{cc}
}

func (c *userInterfaceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/usergrpc.UserInterface/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInterfaceClient) SaveUser(ctx context.Context, in *SaveUserRequest, opts ...grpc.CallOption) (*SaveUserResponse, error) {
	out := new(SaveUserResponse)
	err := c.cc.Invoke(ctx, "/usergrpc.UserInterface/SaveUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInterfaceClient) FindByEmailAndPassword(ctx context.Context, in *FindByEmailAndPasswordRequest, opts ...grpc.CallOption) (*FindByEmailAndPasswordResponse, error) {
	out := new(FindByEmailAndPasswordResponse)
	err := c.cc.Invoke(ctx, "/usergrpc.UserInterface/FindByEmailAndPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInterfaceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/usergrpc.UserInterface/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInterfaceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/usergrpc.UserInterface/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserInterfaceServer is the server API for UserInterface service.
type UserInterfaceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	SaveUser(context.Context, *SaveUserRequest) (*SaveUserResponse, error)
	FindByEmailAndPassword(context.Context, *FindByEmailAndPasswordRequest) (*FindByEmailAndPasswordResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
}

// UnimplementedUserInterfaceServer can be embedded to have forward compatible implementations.
type UnimplementedUserInterfaceServer struct {
}

func (*UnimplementedUserInterfaceServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserInterfaceServer) SaveUser(ctx context.Context, req *SaveUserRequest) (*SaveUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveUser not implemented")
}
func (*UnimplementedUserInterfaceServer) FindByEmailAndPassword(ctx context.Context, req *FindByEmailAndPasswordRequest) (*FindByEmailAndPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByEmailAndPassword not implemented")
}
func (*UnimplementedUserInterfaceServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserInterfaceServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}

func RegisterUserInterfaceServer(s *grpc.Server, srv UserInterfaceServer) {
	s.RegisterService(&_UserInterface_serviceDesc, srv)
}

func _UserInterface_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInterfaceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usergrpc.UserInterface/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInterfaceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInterface_SaveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInterfaceServer).SaveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usergrpc.UserInterface/SaveUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInterfaceServer).SaveUser(ctx, req.(*SaveUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInterface_FindByEmailAndPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByEmailAndPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInterfaceServer).FindByEmailAndPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usergrpc.UserInterface/FindByEmailAndPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInterfaceServer).FindByEmailAndPassword(ctx, req.(*FindByEmailAndPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInterface_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInterfaceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usergrpc.UserInterface/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInterfaceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInterface_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInterfaceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usergrpc.UserInterface/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInterfaceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "usergrpc.UserInterface",
	HandlerType: (*UserInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserInterface_GetUser_Handler,
		},
		{
			MethodName: "SaveUser",
			Handler:    _UserInterface_SaveUser_Handler,
		},
		{
			MethodName: "FindByEmailAndPassword",
			Handler:    _UserInterface_FindByEmailAndPassword_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserInterface_DeleteUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserInterface_UpdateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usergrpc.proto",
}
